# Gluten, Cacahuetes, Crustaceos, Frutos secos, Moluscos, Soja, Pescado, Sesamo, Huevo, Altramuces, Apio, Leche, Mostaza, Anhídrido sulfuroso
alimentos = [
    {"nombre":"agua", "nutriscore":"A", "alergenos":""},
    {"nombre":"nutella", "nutriscore":"E", "alergenos":"leche, soja, frutos secos"},
    {"nombre":"avecrem de verdura", "nutriscore":"D", "alergenos":"huevos, soja, apio"},
    {"nombre":"cocacola zero", "nutriscore":"B", "alergenos":""},
    {"nombre":"cocacola", "nutriscore":"E", "alergenos":""},
    {"nombre":"corn flakes", "nutriscore":"B", "alergenos":"gluten, frutos secos, cacahuetes, soja, sesamo"},
    {"nombre":"yogur natural", "nutriscore":"A", "alergenos":"leche"},
    {"nombre":"yogur griego", "nutriscore":"C", "alergenos":"leche"},
    {"nombre":"nocilla", "nutriscore":"E", "alergenos":"leche, soja, frutos secos"},
    {"nombre":"galletas oreo", "nutriscore":"E", "alergenos":"leche, soja, trigo, gluten"},
    {"nombre":"gazpacho alvalle", "nutriscore":"A", "alergenos":"gluten"},
    {"nombre":"atun calvo", "nutriscore":"B", "alergenos":"crustaceos"},
    {"nombre":"zumosol naranja", "nutriscore":"C", "alergenos":""},
    {"nombre":"helado maxibon", "nutriscore":"D", "alergenos":"frutos secos, leche"},
    {"nombre":"aceite carbonell", "nutriscore":"C", "alergenos":""},
    {"nombre":"garbanzos luengo", "nutriscore":"B", "alergenos":"soja"},
    {"nombre":"agua con gas", "nutriscore":"B", "alergenos":""},
]